export default function businessesJson (extraState, sort) {
    let exportState = [
        {
            id: 1,
            expanded: false,
            name:'Example Company',
            email: 'johna321123@gmail.com',//'volunteering@mixological.co',
            website: 'www.examplecompany.org',
            photo: require('./components/pages/mainpage/businessphotos/bizimage.jpg'),
            hours:'20 hours',
            summary:'Brief summary.',
            location: '5728 SW 57 AVE',
            volunteersNeeded: '30 Volunteers',
            ageWindow: '16-24 years old',
            dailyServiceHours: '6 hours per day',
            totalProjectServiceHours: '72 hours',
            credentials: '',
            gpa: '3.5',
            certficiation: 'MDCPS Volunteer Certification',
            talents: 'Chess and swimming',
            languages: 'English, Spanish',
            dressCode: 'Business casual',
            anyFurtherSpecifications: 'Must take required orientation course'
        },
        {
            id: 2,
            expanded: false,
            name:'Business Name 2',
            email: 'johnisawesome53@gmail.com',
            website: 'examplecompany.org',
            photo: require('./components/pages/mainpage/businessphotos/bizimage.jpg'),
            hours:'20 hours',
            summary:'Brief summary.',
            location: '',
            volunteersNeeded: 'Please volunteer for us.',
            dailyServiceHours: '',
            totalProjectServiceHours: '',
            credentials: '',
            gpa: '',
            certficiation: '',
            talents: '',
            languages: '',
            dressCode: '',
            anyFurtherSpecifications: ''
        },
         {  id: 3,
            expanded: false,
            name:'Business Name 3',
            email: '',
            website: 'examplecompany.org',
            photo: require('./components/pages/mainpage/businessphotos/bizimage.jpg'),
            hours:'20 hours',
            summary:'Brief summary.',
            location: '',
            volunteersNeeded: '',
            dailyServiceHours: '',
            totalProjectServiceHours: '',
            credentials: '',
            gpa: '',
            certficiation: '',
            talents: '',
            languages: '',
            dressCode: '',
            anyFurtherSpecifications: ''
        }, {
            id: 4,
            expanded: false,
            name:'Business Name 4',
            email: '',
            website: 'examplecompany.org',
            photo: require('./components/pages/mainpage/businessphotos/bizimage.jpg'),
            hours:'20 hours',
            summary:'Brief summary.',
            location: '',
            volunteersNeeded: '',
            dailyServiceHours: '',
            totalProjectServiceHours: '',
            credentials: '',
            gpa: '',
            certficiation: '',
            talents: '',
            languages: '',
            dressCode: '',
            anyFurtherSpecifications: ''
        }, {
            id: 5,
            expanded: false,
            name:'Business Name 5',
            email: '',
            website: 'examplecompany.org',
            photo: require('./components/pages/mainpage/businessphotos/bizimage.jpg'),
            hours:'20 hours',
            summary:'Brief summary.',
            location: '',
            volunteersNeeded: '',
            dailyServiceHours: '',
            totalProjectServiceHours: '',
            credentials: '',
            gpa: '',
            certficiation: '',
            talents: '',
            languages: '',
            dressCode: '',
            anyFurtherSpecifications: ''
        },{
            id: 6,
            expanded: false,
            name:'Business Name 6',
            email: '',
            website: 'examplecompany.org',
            photo: require('./components/pages/mainpage/businessphotos/bizimage.jpg'),
            hours:'20 hours',
            summary:'Brief summary.',
            location: '',
            volunteersNeeded: '',
            dailyServiceHours: '',
            totalProjectServiceHours: '',
            credentials: '',
            gpa: '',
            certficiation: '',
            talents: '',
            languages: '',
            dressCode: '',
            anyFurtherSpecifications: ''
        },{
            id: 7,
            expanded: false,
            name:'Business Name 7',
            email: '',
            website: 'examplecompany.org',
            photo: require('./components/pages/mainpage/businessphotos/bizimage.jpg'),
            hours:'20 hours',
            summary:'Brief summary.',
            location: '',
            volunteersNeeded: '',
            dailyServiceHours: '',
            totalProjectServiceHours: '',
            credentials: '',
            gpa: '',
            certficiation: '',
            talents: '',
            languages: '',
            dressCode: '',
            anyFurtherSpecifications: ''
        }, {
            id: 8,
            expanded: false,
            name:'Business Name 8',
            email: '',
            website: 'examplecompany.org',
            photo: require('./components/pages/mainpage/businessphotos/bizimage.jpg'),
            hours:'20 hours',
            summary:'Brief summary.',
            location: '',
            volunteersNeeded: '',
            dailyServiceHours: '',
            totalProjectServiceHours: '',
            credentials: '',
            gpa: '',
            certficiation: '',
            talents: '',
            languages: '',
            dressCode: '',
            anyFurtherSpecifications: ''
        }
    ];

    if (extraState) {
        Object.entries(extraState).forEach(([key,value])=>{
            exportState[key] = value;
        });
    }
    
    return exportState;
}