export default function businessesJson (extraState, sort) {
    let exportState = [
        {
            id: 1,
            expanded: false,
            name:'Example Company',
            email: 'johna321123@gmail.com',//'volunteering@mixological.co',
            website: 'www.examplecompany.org',
            photo: require('./components/pages/mainpage/businessphotos/bizimage.jpg'),
            hours:'20 hours',
            summary:'Brief summary.',
            location: '5728 SW 57 AVE',
            volunteersNeeded: '30 Volunteers',
            ageWindow: '16-24 years old',
            dailyServiceHours: '',
            Sunday: 'N/A',
            Monday: '3-6 PM',
            Tuesday: '3-8 PM',
            Wednesday: '3-6 PM',
            Thursday: '3-8 PM',
            Friday: '3-6 PM',
            Saturday: 'N/A',
            totalProjectServiceHours: '72 hours',
            dates: '12/20/19 - 1/20/20',
            jobTitle: 'Caretaker',
            jobDescription: 'Attend nursing home and assist employees in the workplace.',
            credentials: '',
            gpa: '3.5',
            certficiation: 'MDCPS Volunteer Certification',
            talents: 'Chess and swimming',
            languages: 'English, Spanish',
            dressCode: 'Business casual',
            anyFurtherSpecifications: 'Must take required orientation course'
        },
        {
            id: 2,
            expanded: false,
            name:'Business Name 2',
            email: '',//'volunteering@mixological.co',
            website: '',
            photo: require('./components/pages/mainpage/businessphotos/bizimage.jpg'),
            hours:'20 hours',
            summary:'Brief summary.',
            location: '',
            volunteersNeeded: '',
            ageWindow: '',
            dailyServiceHours: '',
            Sunday: '',
            Monday: '',
            Tuesday: '',
            Wednesday: '',
            Thursday: '',
            Friday: '',
            Saturday: '',
            totalProjectServiceHours: '',
            dates: '',
            jobTitle: '',
            jobDescription: '',
            credentials: '',
            gpa: '',
            certficiation: '',
            talents: '',
            languages: '',
            dressCode: '',
            anyFurtherSpecifications: ''
        },
         {  id: 3,
            expanded: false,
            name:'Business Name 3',
            email: '',//'volunteering@mixological.co',
            website: '',
            photo: require('./components/pages/mainpage/businessphotos/bizimage.jpg'),
            hours:'20 hours',
            summary:'Brief summary.',
            location: '',
            volunteersNeeded: '',
            ageWindow: '',
            dailyServiceHours: '',
            Sunday: '',
            Monday: '',
            Tuesday: '',
            Wednesday: '',
            Thursday: '',
            Friday: '',
            Saturday: '',
            totalProjectServiceHours: '',
            dates: '',
            jobTitle: '',
            jobDescription: '',
            credentials: '',
            gpa: '',
            certficiation: '',
            talents: '',
            languages: '',
            dressCode: '',
            anyFurtherSpecifications: ''
        }, {
            id: 4,
            expanded: false,
            name:'Business Name 4',
            email: '',//'volunteering@mixological.co',
            website: '',
            photo: require('./components/pages/mainpage/businessphotos/bizimage.jpg'),
            hours:'20 hours',
            summary:'Brief summary.',
            location: '',
            volunteersNeeded: '',
            ageWindow: '',
            dailyServiceHours: '',
            Sunday: '',
            Monday: '',
            Tuesday: '',
            Wednesday: '',
            Thursday: '',
            Friday: '',
            Saturday: '',
            totalProjectServiceHours: '',
            dates: '',
            jobTitle: '',
            jobDescription: '',
            credentials: '',
            gpa: '',
            certficiation: '',
            talents: '',
            languages: '',
            dressCode: '',
            anyFurtherSpecifications: ''
        }, {
            id: 5,
            expanded: false,
            name:'Business Name 5',
            email: '',//'volunteering@mixological.co',
            website: '',
            photo: require('./components/pages/mainpage/businessphotos/bizimage.jpg'),
            hours:'20 hours',
            summary:'Brief summary.',
            location: '',
            volunteersNeeded: '',
            ageWindow: '',
            dailyServiceHours: '',
            Sunday: '',
            Monday: '',
            Tuesday: '',
            Wednesday: '',
            Thursday: '',
            Friday: '',
            Saturday: '',
            totalProjectServiceHours: '',
            dates: '',
            jobTitle: '',
            jobDescription: '',
            credentials: '',
            gpa: '',
            certficiation: '',
            talents: '',
            languages: '',
            dressCode: '',
            anyFurtherSpecifications: ''
        },{
            id: 6,
            expanded: false,
            name:'Business Name 6',
            email: '',//'volunteering@mixological.co',
            website: '',
            photo: require('./components/pages/mainpage/businessphotos/bizimage.jpg'),
            hours:'20 hours',
            summary:'Brief summary.',
            location: '',
            volunteersNeeded: '',
            ageWindow: '',
            dailyServiceHours: '',
            Sunday: '',
            Monday: '',
            Tuesday: '',
            Wednesday: '',
            Thursday: '',
            Friday: '',
            Saturday: '',
            totalProjectServiceHours: '',
            dates: '',
            jobTitle: '',
            jobDescription: '',
            credentials: '',
            gpa: '',
            certficiation: '',
            talents: '',
            languages: '',
            dressCode: '',
            anyFurtherSpecifications: ''
        },{
            id: 7,
            expanded: false,
            name:'Business Name 7',
            email: '',//'volunteering@mixological.co',
            website: '',
            photo: require('./components/pages/mainpage/businessphotos/bizimage.jpg'),
            hours:'20 hours',
            summary:'Brief summary.',
            location: '',
            volunteersNeeded: '',
            ageWindow: '',
            dailyServiceHours: '',
            Sunday: '',
            Monday: '',
            Tuesday: '',
            Wednesday: '',
            Thursday: '',
            Friday: '',
            Saturday: '',
            totalProjectServiceHours: '',
            dates: '',
            jobTitle: '',
            jobDescription: '',
            credentials: '',
            gpa: '',
            certficiation: '',
            talents: '',
            languages: '',
            dressCode: '',
            anyFurtherSpecifications: ''
        }, {
            id: 8,
            expanded: false,
            name:'Business Name 8',
            email: '',//'volunteering@mixological.co',
            website: '',
            photo: require('./components/pages/mainpage/businessphotos/bizimage.jpg'),
            hours:'20 hours',
            summary:'Brief summary.',
            location: '',
            volunteersNeeded: '',
            ageWindow: '',
            dailyServiceHours: '',
            Sunday: '',
            Monday: '',
            Tuesday: '',
            Wednesday: '',
            Thursday: '',
            Friday: '',
            Saturday: '',
            totalProjectServiceHours: '',
            dates: '',
            jobTitle: '',
            jobDescription: '',
            credentials: '',
            gpa: '',
            certficiation: '',
            talents: '',
            languages: '',
            dressCode: '',
            anyFurtherSpecifications: ''
        }
    ];

    if (extraState) {
        Object.entries(extraState).forEach(([key,value])=>{
            exportState[key] = value;
        });
    }
    
    return exportState;
}